name: Deploy AWS Lambda via Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Limpar build anterior (se existir)
        run: |
          rm -f check_user.zip
          rm -rf build || true

      - name: Preparar pacote Lambda compatível (via Docker AWS SAM build image)
        run: |
          mkdir -p build
          cp -r check_user/* build/
          
          docker run --rm -v "$PWD/build":/var/task public.ecr.aws/sam/build-python3.10 bash -c "\
            pip install -r /var/task/requirements.txt -t /var/task && \
            cd /var/task && \
            zip -r lambda.zip ."
          
          cp build/lambda.zip check_user.zip


      - name: Verificar conteúdo do .zip
        run: unzip -l check_user.zip

      - name: Forçar remoção da pasta build via Docker (caso permissões bloqueiem)
        run: |
          docker run --rm -v "$PWD":/mnt amazonlinux:2 bash -c "rm -rf /mnt/build"

      - name: Inicializar o Terraform
        run: terraform init

      - name: Importar recursos existentes com timeout (30s)
        run: |
          timeout 30s terraform import aws_lambda_function.check_user check-user || true
          timeout 30s terraform import aws_apigatewayv2_api.auth 06vrwdm931 || true
          timeout 30s terraform import aws_apigatewayv2_stage.default 06vrwdm931/$default || true
          timeout 30s terraform import aws_apigatewayv2_integration.lambda_integration 06vrwdm931/xxbygpq || true
          timeout 30s terraform import aws_apigatewayv2_route.auth_route 06vrwdm931/kjhwxon || true
          timeout 30s terraform import aws_lambda_permission.allow_apigw check-user/AllowInvoke || true

      - name: Validar o Terraform
        run: terraform validate

      - name: Aplicar alterações com Terraform
        run: terraform apply -auto-approve
