name: Deploy AWS Lambda via Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Compactar a função Lambda
        run: |
          cd lambda/check_user
          zip -r ../check_user.zip .
          cd ..

      - name: Inicializar o Terraform
        working-directory: lambda
        run: terraform init

      - name: Validar o Terraform
        working-directory: lambda
        run: terraform validate

      - name: Aplicar alterações com Terraform
        working-directory: lambda
        run: terraform apply -auto-approve
