name: Deploy AWS Lambda via Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Limpar build anterior (se existir)
        run: |
          if [ -f check_user.zip ]; then rm check_user.zip; fi
          if [ -d check_user/__pycache__ ]; then rm -rf check_user/__pycache__; fi

      - name: Instalar dependências
        run: |
          pip install -r check_user/requirements.txt -t check_user/

      - name: Compactar a função Lambda
        run: |
          cd check_user
          zip -r ../check_user.zip .

      - name: Verificar conteúdo do .zip
        run: unzip -l check_user.zip

      - name: Inicializar o Terraform
        run: terraform init

      - name: Importar recursos existentes (dinâmico)
        run: |
          terraform import aws_lambda_function.check_user check-user || true
          terraform import aws_apigatewayv2_api.auth 06vrwdm931 || true
          terraform import aws_apigatewayv2_stage.default 06vrwdm931/\$default || true
          terraform import aws_apigatewayv2_integration.lambda_integration 06vrwdm931/xxbygpq || true
          terraform import aws_apigatewayv2_route.auth_route 06vrwdm931/kjhwxon || true
          terraform import aws_lambda_permission.allow_apigw check-user/AllowInvoke || true

      - name: Validar o Terraform
        run: terraform validate

      - name: Validar o Terraform
        run: terraform validate

      - name: Aplicar alterações com Terraform
        run: terraform apply -auto-approve
