name: Deploy AWS Lambda via Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Limpar build anterior (se existir)
        run: |
          rm -f check_user.zip
          rm -rf build

      - name: Preparar pacote Lambda compatível (via Docker Amazon Linux 2)
        run: |
          mkdir -p build
          cp -r check_user/* build/
          
          docker run --rm -v "$PWD/build":/var/task \
            amazonlinux:2 bash -c "\
              yum install -y gcc postgresql-devel python3 python3-devel zip && \
              pip3 install --upgrade pip && \
              pip3 install -r /var/task/requirements.txt -t /var/task && \
              cd /var/task && \
              zip -r check_user.zip . && \
              chown -R 1000:1000 /var/task/*"

      - name: Mover .zip para raiz do projeto
        run: mv build/check_user.zip check_user.zip

      - name: Verificar conteúdo do .zip
        run: unzip -l check_user.zip

      - name: Limpar build temporário
        run: rm -rf build

      - name: Inicializar o Terraform
        run: terraform init

      - name: Importar recursos existentes (dinâmico)
        run: |
          terraform import aws_lambda_function.check_user check-user || true
          terraform import aws_apigatewayv2_api.auth 06vrwdm931 || true
          terraform import aws_apigatewayv2_stage.default 06vrwdm931/\$default || true
          terraform import aws_apigatewayv2_integration.lambda_integration 06vrwdm931/xxbygpq || true
          terraform import aws_apigatewayv2_route.auth_route 06vrwdm931/kjhwxon || true
          terraform import aws_lambda_permission.allow_apigw check-user/AllowInvoke || true

      - name: Validar o Terraform
        run: terraform validate

      - name: Aplicar alterações com Terraform
        run: terraform apply -auto-approve
